version: '3'

# networks:
#     default:
#         external:
#             name: hyproxy

services:
    web:
        build: ./docker/nginx/
        depends_on:
            - php
        volumes:
            - .:/sharetoall
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        environment:
            - VIRTUAL_HOST=sharetoall.loc
            - VIRTUAL_PORT=80

    php:
        build: ./docker/php/
        depends_on:
            - db
            - redis
        volumes:
            - ./:/sharetoall
            - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
    redis:
        image: redis:3-alpine

    db:
        image: mariadb:latest
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: sharetoall
            MYSQL_PASSWORD: sharetoall
            MYSQL_DATABASE: sharetoall

    mailhog:
        image: mailhog/mailhog
        ports:
            - 8030:8030

    # webdriver:
    #     image: selenium/standalone-chrome
    #     ports:
    #         - "4567:4444"
    #     external_links:
    #         - hyproxy_nginx-proxy_1:sharetoall.loc
