version: '2'

services:
    web:
        image: registry.gitlab.com/phantas0s/sharetoall:web-latest
        ports:
            - 9090:80
        depends_on:
            - php
        environment:
            - VIRTUAL_HOST=sharetoall.com www.sharetoall.com
            - VIRTUAL_PORT=80
        volumes:
            - public:/sharetoall/web

    php:
        image: registry.gitlab.com/phantas0s/sharetoall:php-latest
        volumes:
            - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
            - public:/sharetoall/web
        depends_on:
            - redis
        env_file:
            - config.env

    redis:
        image: registry.gitlab.com/phantas0s/sharetoall:redis-latest

volumes:
    public:
