parameters:
    db.options:
        host: "%db.host%"
        port: "%db.port%"
        dbname: "%db.name%"
        user: "%db.user%"
        password: "%db.password%"
    features:
        example: %feature.example%
