services:
    form.options:
        class: InputValidation\Form\Options\JsonOptions
        arguments:
            - "@translator"
        calls:
            - [setOptionsPath, ["%app.path%/options"]]

    form.validator:
        class: InputValidation\Form\Validator

    form.factory:
        class: App\Form\FormFactory
        arguments:
            - "@translator"
            - "@form.validator"
            - "@form.options"
        calls:
            - [setFactoryNamespace, ['App\Form']]
            - [setFactoryPostfix, ['Form']]

    form.newsletter:
        class: App\Form\User\NewsletterForm
        arguments:
            - "@translator"
            - "@form.validator"
            - "@form.options"

    form.contact:
        class: App\Form\Contact\CreateForm
        arguments:
            - "@translator"
            - "@form.validator"
            - "@form.options"
